[package]
name = "uplc"
version = "0.1.0"
edition = "2021"

[dependencies]
blst = "0.3.13"
bumpalo = { version = "3.16.0", features = ["collections"] }
chumsky = { version = "1.0.0-alpha.7", features = ["pratt"] }
rug = { version = "1.26.0", default-features = false, features = [
    "integer",
    "std",
] }
thiserror = "1.0.63"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
insta = "1.40.0"
ouroboros = "0.18.4"
pretty_assertions = "1.4.0"
uplc_macros = { version = "0.1.0", path = "../uplc_macros" }

[[bench]]
name = "bench_main"
harness = false
